Release/1.0.27 (#428)
* Release 1.0.27 - Create base branch

* Fix for #347 (include in LiveList) (#348)

* LiveList: reload included objects

First implementation

* Key was wrong on order change

* include sub-includes

* reuse loaded pointers

* Deleted stuff

* LiveList autoupdate included sub-objects (#349)

* LiveList: reload included objects

First implementation

* Key was wrong on order change

* include sub-includes

* reuse loaded pointers

* Deleted stuff

* Adding listening on included objects to LiveList

* Updated readme for ParseLiveList

* Update parse_live_list.dart

* LiveList: sync subObjects after reconnect (#352)

* Sync subObjects after reconnect

* Update README.md

* Update README.md (#353)

* ISSUE-351: Replaced isTypeOfException with Exception (#355)

Great work! Thank you

* RegisterSubClass and smaler changes (#368)

* added subclass handler

* integraded subclass handler

* added constructor for QueryBuilder using registered SubClasses

* subclass handler optimizations

* Convenience changes

* Convenience change

* sembast CoreStore on macos

* Fix: ParseUser updated on server but not locally

This should be a fix for:
https://github.com/parse-community/Parse-SDK-Flutter/issues/364
and
https://github.com/parse-community/Parse-SDK-Flutter/issues/256

* Update README.md

* Update README.md

* Update README.md (#367)

* Save installationId when new installation created. Send installationId when User login (#375)

* ParseLiveElement (#376)

* First implementation for ParseLiveElement

* ParseLiveElement further implementation

* Update parse_live_list.dart

* ParseLiveElement working

* News methods for ParseQuery -  whereMatchesKeyInQuery and whereDoesNotMatchKeyInQuery (#379)

* Add method whereMatchesKeyInQuery

Add method whereMatchesKeyInQuery

* Update parse_query.dart

* Fix whereMatchesKeyInQuery / whereDoesNotMatchKeyInQuery

* Update README.md

* Update README.md

* Update README.md

* Add google login helper (#387)

- Update README to show how to get google login attributes for parse

* Update parse_response_builder.dart (#390)

* [web] Check web before Platform.isX (#392)

Platform.isX is unsupported in web

* Make web compatible calls for locale and skip PackageInfo (#395)

* Make web compatible calls for locale and skip PackageInfo

* Also get country code for web locale

* Add description of early web support

* Added ParseFile check to _canBeSerialized() (#396)

* Update README.md (#397)

Fix Parse Server parameter name

* ParseLiveList: first implementation of lazyLoading (#407)

Setting lazyLoading=false should disable lazyLoading.

* Update parse_live_list.dart (#406)

In theory this should not make any difference. In practise sometimes an error gets thrown:
The following NoSuchMethodError was thrown while finalizing the widget tree:
The method 'dispose' was called on null.
Receiver: null
Tried calling: dispose()

* File Support for web (#409)

* created files and started implementation

* add different filetypes to sdk

* Update README.md

* add an other file example to README (#410)

* added file example to README

* Update README.md

* Web file upload: set content type to "text/plain" incase neighter name nor url is set (#411)

This breaks the extension at the uploaded file, but otherwise the upload would fail with a server error.

* LiveQuery reconnecting intervals (#414)

* parseFileConstructor was missing at Parse.initialize

* add liveListRetryIntervals to Parse.initialize

* replace kIsWeb with its definition (#415)

Using less libaries is always good.

* release/1.0.27 update dependencies

* Release/1.0.27 (#427)

* forgetLocalSession before login / signUP / loginAnonymous #426

* forgetLocalSession before login / signUP / loginAnonymous #426

* Release 1.0.27 - Pre-release process
- Update dependencies

* Release 1.0.27 - Pre-release process
- Static analysis fixes

Co-authored-by: Maximilian Fischer <45403027+maaeps@users.noreply.github.com>
Co-authored-by: Michal Baran <baranmichal25@gmail.com>
Co-authored-by: Maximilian Fischer <github@maaeps.de>
Co-authored-by: Phani Rithvij <phanirithvij2000@gmail.com>
Co-authored-by: Danaru <danaru@tuta.io>
Co-authored-by: Rodrigo de Souza Marques <rodrigosmarques@gmail.com>
Co-authored-by: vreamer <55081983+vreamer@users.noreply.github.com>
Co-authored-by: Dmytro Karpovych <ZAYEC77@gmail.com>
Co-authored-by: Nils Strelow <1096841+nstrelow@users.noreply.github.com>
Co-authored-by: hyperrecursive <matsko@hyprec.com>