Update parse_live_list.dart (#406)
In theory this should not make any difference. In practise sometimes an error gets thrown:
The following NoSuchMethodError was thrown while finalizing the widget tree:
The method 'dispose' was called on null.
Receiver: null
Tried calling: dispose()